# Generated by Django 6.0.3 on 2026-04-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skill', models.TextField()),
                ('skill_type', models.CharField(default='custom', max_length=100)),
                ('solution', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('payment_status', models.CharField(default='Not Paid', max_length=50)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expert')),
            ],
        ),
    ]
